package com.anfantanion.traintimes1.models.stationResponse

data class LocationDetail(
    val realtimeActivated: Boolean,
    val tiploc: String,
    val crs: String,
    val description: String,
    //val wttBookedArrival : String?,
    //val wttBookedDeparture : String?,
    //val wttBookedPass  : String?,
    val gbttBookedArrival: String,
    val gbttBookedDeparture: String,
    val origin: List<Origin>,
    val destination: List<Destination>,
    val isCall: Boolean,
    val isPublicCall: Boolean,
    val realtimeArrival: String,
    val realtimeArrivalActual: Boolean,
    val realtimeDeparture: String,
    val realtimeDepartureActual: Boolean,
    val displayAs: String,
    val line: String?,
    val lineConfirmed: Boolean?,
    val path: String?,
    val pathConfirmed: Boolean?,
    val platform: String,
    val platformChanged: Boolean,
    val platformConfirmed: Boolean,
    val serviceLocation: String?
)